name: Deploy Models to Jetson

on:
  push:
    branches:
      - dev  # Adjust to your default branch

jobs:
  deploy:
    runs-on: self-hosted  # Use the Jetson runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Model to Jetson
        run: |
          mkdir -p /home/okdot5/JOELEN_MODELS/matilde-models/best_models/
          cp ./pytorch/models/best_models/*.pth /home/okdot5/JOELEN_MODELS/matilde-models/best_models/
          source /home/okdot5/yolovenv/bin/activate
          python /home/okdot5/JOELEN_MODELS/matilde-models/actions_conversion.py /home/okdot5/JOELEN_MODELS/matilde-models/best_models/

      - name: Verify Deployment
        run: |
          ls -lh /home/okdot5/JOELEN_MODELS/matilde-models/best_models/
          echo "Model deployed successfully"
