name: Deploy Models to Jetson

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: self-hosted  #Jetson runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TensorRT
        run: |
          if ! command -v trtexec >/dev/null 2>&1; then
            echo "Installing TensorRT"
            sudo apt-get install -y tensorrt
            trtexec --version
          else
            echo "TensorRT already installed"
          fi

      - name: Deploy Model to Jetson
        run: |
          cp -r /home/okdot5/new_models/best_models/* /home/okdot5/old_models/
          find /home/okdot5/new_models/best_models/ -type f -delete

          cp ./pytorch/models/best_models/*.pth /home/okdot5/new_models/best_models/pth
          source /home/okdot5/yolovenv/bin/activate

          python /home/okdot5/new_models/actions_conversion.py /home/okdot5/new_models/best_models/pth
          cd /home/okdot5/new_models/
          ./convert_trt.sh

      - name: Verify Deployment
        run: |
          ls -lh /home/okdot5/new_models/best_models/trt
