name: Deploy to Jetson Nano

on:
  push:
    branches:
      - jetson_nano_test 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Jetson Nano
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.JETSON_IP }}
          username: ${{ secrets.JETSON_USER }}
          key: ${{ secrets.JETSON_SSH_KEY }}
          script: |
            cd /home/jetson/jetson-nano-tests
            git pull origin jetson-nano-tests
            g++ lane_detection.cpp -o lane_detection `pkg-config --cflags --libs opencv4` -lnvinfer -lnvonnxparser -lcudart
